services:
  keria:
    image: weboftrust/keria
    healthcheck:
        test: ['CMD', 'curl', '-f', 'http://localhost:3902/spec.yaml']
        interval: 2s
        timeout: 3s
        retries: 5
        start_period: 2s

  hio-server:
    build: ./hio-server
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - PORT=8081

  bench:
    depends_on:
      keria:
        condition: service_healthy
    image: jordi/ab
    command: ["-n","100", "-c", "100", "http://keria:3902/spec.yaml"]

  nodejs:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
